### ISSUE TITLE
Разобраться с представлением карты в виде графа

### ISSUE THREAD

**Issue by MLGBrotishka** [mai-806/Delivery.Graph#1]
Для проекта нужно как-то представить граф. Нужно определиться с полями и типами данных.

**Comment by FlyingOwl8** [comment]
Егор лох

**Comment by MLGBrotishka** [comment]
Нашел ссылочку https://habr.com/ru/articles/65367/

**Comment by MLGBrotishka** [comment]
Пока найдено https://www.openstreetmap.org/export#map=15/64.5276/39.7024
https://github.com/AndGem/OsmToRoadGraph

**Comment by MLGBrotishka** [comment]
Еще штука для перевода https://github.com/pgRouting/osm2pgrouting
https://pgrouting.org/

**Comment by volozer** [comment]
https://pyrosm.readthedocs.io/en/latest/graphs.html

**Comment by MLGBrotishka** [comment]
Пока итоговый вариант https://github.com/AndGem/OsmToRoadGraph
