### ISSUE TITLE
Как хранить граф в БД

### ISSUE THREAD

**Issue by MLGBrotishka** [mai-806/Delivery.Graph#2]
Нужно понять пределы бд. Какой наиболее эффективный способ хранения такого графа. Можно ли доставать кусками, как часто можно обращаться к бд с запросами.

**Comment by DmitriMAI** [comment]
А в redis не хотите?

**Comment by MLGBrotishka** [comment]
Нет

С уважением,
Чапкин Владислав

сб, 1 июл. 2023 г., 15:06 DmitriMAI ***@***.***>:

**Comment by MLGBrotishka** [comment]
ахахахаахх

**Comment by MLGBrotishka** [comment]
Решение: разделить граф на куски (чанки). Хранить в бд ключ- номер чанка, значение - содержимое чанка.
